name: Deploy Stage

on:
  push:
    branches: [ stage ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest
    needs: [build_test]
    environment: master

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          IMAGE_TAG: v1-${{ steps.commit_hash.outputs.sha_short }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-actions:${{ steps.vars.outputs.tag }}

  deploy_tencent:
    runs-on: ubuntu-latest
    needs: [push_dockerhub]
    environment: master

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Deploy to Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm upgrade --install stg-sample deployment/sample --set image.tag=${{ steps.vars.outputs.tag }} --set ingress.prefix=stg
