name: Deploy Stage

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies and test
        run: |
          go mod download
          go test ./...
