name: Deploy Master

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy_tencent:
    runs-on: ubuntu-latest
    environment: master

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Deploy to Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm upgrade --install sample deployment/sample --set image.tag=${{ steps.vars.outputs.tag }}
