name: Deploy Master

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest
    environment: master

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-actions:master

  deploy_tencent:
    runs-on: ubuntu-latest
    needs: [push_dockerhub]
    environment: master

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Deploy to Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm upgrade --install sample deployment/sample --set image.tag=master
